baseurl: /pythonic

collections:
  getting_started:
    output: true
  python:
    output: true
  parallel_computing:
    output: true
  numpy:
    output: true
  flask:
    output: true
  matplotlib:
    output: true
  scipy:
    output: true
  tkinter:
    output: true

defaults:
  - scope:
      path: ""
      type: "getting_started"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "python"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "parallel_computing"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "numpy"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "flask"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "matplotlib"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "scipy"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "tkinter"
    values:
      layout: "page"

exclude: [Gemfile]
